import { useState } from 'react';
import { Link, NavLink } from 'react-router-dom';
import { FileStack, Menu, X, ArrowUpRight } from 'lucide-react';
import { tools } from '@/config/tools';

export function Header() { const [open, setOpen] = useState(false); const nav = [['Home','/'],['All Tools','/tools'],['PDF Tools','/pdf-tools'],['Office Tools','/office-tools'],['Image Tools','/image-tools']]; return <header className="site-header"><div className="shell nav-wrap"><Link to="/" className="brand"><span className="brand-mark"><FileStack size={21}/></span><span>File<span>Nova</span></span></Link><nav className="desktop-nav">{nav.map(([label, path]) => <NavLink key={path} to={path} className={({isActive}) => isActive ? 'nav-link active' : 'nav-link'}>{label}</NavLink>)}</nav><div className="desktop-cta"><Link to="/tools" className="button-primary small">All Tools <ArrowUpRight size={16}/></Link></div><button className="mobile-menu" aria-label="Toggle navigation" onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div>{open && <nav className="mobile-nav">{nav.map(([label, path]) => <NavLink onClick={() => setOpen(false)} key={path} to={path} className="nav-link">{label}</NavLink>)}</nav>}</header>; }

export function AdBanner({ variant = 'banner' }: { variant?: 'banner'|'rectangle'|'mobile' }) { return <div className={`ad-placeholder ad-${variant}`} aria-label="Advertisement placeholder"><span>Advertisement</span></div>; }

export function Footer() { return <footer className="footer"><div className="shell footer-grid"><div className="footer-brand"><Link to="/" className="brand"><span className="brand-mark"><FileStack size={19}/></span><span>File<span>Nova</span></span></Link><p>Free online file conversion and PDF tools.</p></div><div><h3>Tools</h3><div className="footer-links">{tools.slice(0,6).map((tool) => <Link key={tool.id} to={tool.route}>{tool.name}</Link>)}</div></div><div><h3>Categories</h3><div className="footer-links"><Link to="/pdf-tools">PDF Tools</Link><Link to="/office-tools">Office Tools</Link><Link to="/image-tools">Image Tools</Link></div></div><div><h3>Company</h3><div className="footer-links"><Link to="/about">About</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></div></div></div><div className="shell footer-bottom"><span>© {new Date().getFullYear()} FileNova. Built for simple file workflows.</span><span>Your files are never saved to an account or history.</span></div></footer>; }

export function Shell({ children }: { children: React.ReactNode }) { return <><Header/><main>{children}</main><Footer/></>; }
